### ISSUE TITLE
Merge multiple

### ISSUE THREAD

**Issue by nam-co** [VineCode/JsMin.novaextension#1]
Hi, thanks for the extension, I was wondering if there's a way to merge files, for example a @ import('some other js file path'), something like code kit has

Thanks

**Comment by vinecode-andy** [comment]
Hi @nam-co, at the moment no and I didn't have plans to add this. I tend to use include.js for loading multiple files. I will add it to the wish list and have a think about how this could be implemented. Someone expressed interest in creating a codekit plug-in, might be one to watch https://twitter.com/bdkjones/status/1304158421336207360
